version: '3'
volumes:
  pg_sso:
services:
  pg:
    image: postgres
    volumes:
      - pg_sso:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sso_db
      POSTGRES_USER: sso_user
      POSTGRES_PASSWORD: sso_password
    ports:
      - 5432:5432
  sso:
    image: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8
    #image: registry.access.redhat.com/redhat-sso-7/sso73-openshift
    #image: jboss/keycloak:9.0.2
    environment:
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: admin
    ports:
    - 8080:8080
    - 9990:9990
    depends_on:
    - pg
  ldap:
    container_name: ldap-container
    build: ldap
    image: rh-sso-lab/ldap
    ports:
    - 1389:389
